// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func ArrowTurnLeftDownSolid(p icons.IconProps) htmx.Node {
<<<<<<< HEAD
    return htmx.SVG(
=======
	return htmx.SVG(
>>>>>>> 6e89f91 (feat(plugin): render proto)
        htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
        htmx.Attribute("viewBox", "0 0 24 24"),
        htmx.Merge(
            htmx.ClassNames{
                "h-5": false,
                "h-6": true,
                "w-5": false,
                "w-6": true,
            },
            p.ClassNames,
        ),
        htmx.Path(
            htmx.Attribute("d", "M20.2397 3.75001C20.2397 4.16423 19.9039 4.50002 19.4897 4.50002L8.98877 4.50002L8.98877 18.4389L11.4588 15.9693C11.7517 15.6764 12.2266 15.6764 12.5195 15.9693C12.8124 16.2622 12.8123 16.7371 12.5194 17.03L8.76906 20.7799C8.47616 21.0727 8.00131 21.0727 7.7084 20.7799L3.95804 17.03C3.66512 16.7371 3.6651 16.2622 3.95799 15.9693C4.25089 15.6764 4.72578 15.6764 5.0187 15.9693L7.4887 18.4389L7.4887 3.75001C7.4887 3.33579 7.8245 3 8.23873 3L19.4897 3C19.9039 3 20.2397 3.33579 20.2397 3.75001Z"),
        ),
    )
}
