// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func MoonMicroSolid(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
        htmx.Attribute("viewBox", "0 0 16 16"),
        htmx.Attribute("fill", "none"),
        htmx.Merge(
            htmx.ClassNames{
                "h-4": true,
                "w-4": true,
            },
            p.ClassNames,
        ),
        htmx.Path(
            htmx.Attribute("d", "M14.438 10.1477C14.6278 9.72286 14.1166 9.36124 13.6899 9.54667C13.0188 9.83824 12.2783 9.9999 11.5 9.9999C8.46243 9.9999 6 7.53747 6 4.4999C6 3.72165 6.16164 2.98114 6.45319 2.31014C6.63861 1.88337 6.27698 1.37223 5.85212 1.56197C3.58205 2.57578 2 4.85312 2 7.49997C2 11.0898 4.91015 14 8.5 14C11.1469 14 13.4243 12.4179 14.438 10.1477Z"),
        ),
    )
}
