// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func SlashMicroSolid(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
        htmx.Attribute("viewBox", "0 0 16 16"),
        htmx.Merge(
            htmx.ClassNames{
            },
            p.ClassNames,
        ),
        htmx.Path(
            htmx.Attribute("d", "M10.0741 2.04731C10.4634 2.18887 10.6642 2.61919 10.5227 3.00846L6.70505 13.5069C6.56349 13.8962 6.13317 14.097 5.7439 13.9555C5.35462 13.8139 5.1538 13.3836 5.29536 12.9943L9.11299 2.49585C9.25454 2.10657 9.68486 1.90576 10.0741 2.04731Z"),
        ),
    )
}
