// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func ArrowsCrossingOutline(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
		htmx.Attribute("viewBox", "0 0 24 24"),
		htmx.Merge(
			htmx.ClassNames{
				"h-5": true,
				"h-6": false,
				"w-5": true,
				"w-6": false,
			},
			p.ClassNames,
		),
		htmx.Path(
			htmx.Attribute("stroke-linecap", "round"),
			htmx.Attribute("stroke-linejoin", "round"),
			htmx.Attribute("d", "m 17,16 h 4 M 18.25,18.75 21,16 m 0,0 -2.75,-2.75 M 17,16 c -2.489742,0 -3.984616,-0.612231 -5.035053,-1.497957 M 8.0350528,9.497957 C 6.9846162,8.6122307 5.4897418,8 3,8 m 14,0 h 4 M 17,8 C 8,8 12,16 3,16 M 18.25,5.25 21,8 m 0,0 -2.75,2.75"),
		),
	)
}
