// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func BadgeOutline(p icons.IconProps) htmx.Node {
    return htmx.SVG(
        htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
        htmx.Attribute("viewBox", "0 0 24 24"),
        htmx.Merge(
            htmx.ClassNames{
                "h-5": true,
                "h-6": false,
                "w-5": true,
                "w-6": false,
            },
            p.ClassNames,
        ),
        htmx.Path(
            htmx.Attribute("stroke-linecap", "round"),
            htmx.Attribute("stroke-linejoin", "round"),
            htmx.Attribute("d", "m 21,12 c 0,1.2683 -0.6296,2.3895 -1.5933,3.0682 0.2014,1.1612 -0.1463,2.399 -1.043,3.2957 -0.8967,0.8967 -2.1345,1.2444 -3.2957,1.043 C 14.3893,20.3705 13.2682,21 12,21 10.7319,21 9.61072,20.3705 8.93204,19.407 7.77066,19.6086 6.53256,19.261 5.6357,18.3641 4.73886,17.4673 4.39125,16.2292 4.59286,15.0678 3.62941,14.3891 3,13.2681 3,12 3,10.7319 3.62946,9.61077 4.59298,8.93208 4.39147,7.77079 4.7391,6.53284 5.63587,5.63607 6.53265,4.73929 7.77063,4.39166 8.93194,4.59319 9.61061,3.62955 10.7318,3 12,3 c 1.2682,0 2.3893,0.6295 3.068,1.59307 1.1614,-0.20162 2.3994,0.14599 3.2963,1.04283 0.8968,0.89684 1.2444,2.13491 1.0428,3.29628 C 20.3706,9.61087 21,10.7319 21,12 Z"),
        ),
    )
}
