// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func BlockquoteSolid(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
		htmx.Attribute("viewBox", "0 0 24 24"),
		htmx.Merge(
			htmx.ClassNames{
				"h-5": false,
				"h-6": true,
				"w-5": false,
				"w-6": true,
			},
			p.ClassNames,
		),
		htmx.Path(
			htmx.Attribute("d", "M 3.75,3.25 A 0.75,0.75 0 0 0 3,4 V 20 A 0.75,0.75 0 0 0 3.75,20.75 0.75,0.75 0 0 0 4.5,20 V 4 A 0.75,0.75 0 0 0 3.75,3.25 Z m 4.5,2 A 0.75,0.75 0 0 0 7.5,6 0.75,0.75 0 0 0 8.25,6.75 h 12 A 0.75,0.75 0 0 0 21,6 0.75,0.75 0 0 0 20.25,5.25 Z m 0,6 A 0.75,0.75 0 0 0 7.5,12 0.75,0.75 0 0 0 8.25,12.75 h 12 A 0.75,0.75 0 0 0 21,12 0.75,0.75 0 0 0 20.25,11.25 Z m 0,6 A 0.75,0.75 0 0 0 7.5,18 0.75,0.75 0 0 0 8.25,18.75 H 16.5 A 0.75,0.75 0 0 0 17.25,18 0.75,0.75 0 0 0 16.5,17.25 Z"),
		),
	)
}
