// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func ChecklistBoxesOutline(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
		htmx.Attribute("viewBox", "0 0 24 24"),
		htmx.Merge(
			htmx.ClassNames{
				"h-5": true,
				"h-6": false,
				"w-5": true,
				"w-6": false,
			},
			p.ClassNames,
		),
		htmx.Path(
			htmx.Attribute("stroke-linecap", "round"),
			htmx.Attribute("stroke-linejoin", "round"),
			htmx.Attribute("d", "m 3.75,16.25 h 3.5 v 3.5 h -3.5 z m 0,-6 h 3.5 v 3.5 h -3.5 z m 10e-8,-4.0356939 L 5.0625,7.5000261 7.25,4.5000131 m 2.75,1.5 H 20.25 M 10,12.000013 h 10.25 m -10.25,6 h 10.25"),
		),
	)
}
