// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func ChevronDownUpSolid(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
		htmx.Attribute("viewBox", "0 0 24 24"),
		htmx.Merge(
			htmx.ClassNames{
				"h-5": false,
				"h-6": true,
				"w-5": false,
				"w-6": true,
			},
			p.ClassNames,
		),
		htmx.Path(
			htmx.Attribute("d", "m 11.460316,9.5119517 a 0.75,0.75 0 0 0 1.06,0 l 3.75,-3.75 a 0.75,0.75 0 0 0 -1.06,-1.06 l -3.22,3.22 -3.2200002,-3.22 a 0.75,0.75 0 0 0 -1.06,1.06 z M 7.7103159,19.260632 a 0.75,0.75 0 0 0 1.06,0 l 3.2200001,-3.22 3.22,3.22 a 0.75,0.75 0 1 0 1.06,-1.06 l -3.75,-3.75 a 0.75,0.75 0 0 0 -1.06,0 l -3.7500002,3.75 a 0.75,0.75 0 0 0 1e-7,1.06 z"),
		),
	)
}
