// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func Dots2X2Solid(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
		htmx.Attribute("viewBox", "0 0 24 24"),
		htmx.Merge(
			htmx.ClassNames{
				"h-5": false,
				"h-6": true,
				"w-5": false,
				"w-6": true,
			},
			p.ClassNames,
		),
		htmx.Path(
			htmx.Attribute("d", "m 16.5,9 c 0,-0.819559 -0.680441,-1.5 -1.5,-1.5 -0.819559,0 -1.5,0.680441 -1.5,1.5 0,0.819559 0.680441,1.5 1.5,1.5 0.819559,0 1.5,-0.680441 1.5,-1.5 z m 0,6 c 0,-0.819559 -0.680441,-1.5 -1.5,-1.5 -0.819559,0 -1.5,0.680441 -1.5,1.5 0,0.819559 0.680441,1.5 1.5,1.5 0.819559,0 1.5,-0.680441 1.5,-1.5 z m -6,-6 C 10.5,8.180441 9.819559,7.5 9,7.5 8.180441,7.5 7.5,8.180441 7.5,9 c 0,0.819559 0.680441,1.5 1.5,1.5 0.819559,0 1.5,-0.680441 1.5,-1.5 z m 0,6 c 0,-0.819559 -0.680441,-1.5 -1.5,-1.5 -0.819559,0 -1.5,0.680441 -1.5,1.5 0,0.819559 0.680441,1.5 1.5,1.5 0.819559,0 1.5,-0.680441 1.5,-1.5 z"),
		),
	)
}
