// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func FloppyDiskSolid(p icons.IconProps) htmx.Node {
    return htmx.SVG(
        htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
        htmx.Attribute("viewBox", "0 0 24 24"),
        htmx.Merge(
            htmx.ClassNames{
                "h-5": false,
                "h-6": true,
                "w-5": false,
                "w-6": true,
            },
            p.ClassNames,
        ),
        htmx.Path(
            htmx.Attribute("d", "M 13.25,5 A 0.75,0.75 0 0 0 12.5,5.75 v 2.5 A 0.75,0.75 0 0 0 13.25,9 0.75,0.75 0 0 0 14,8.25 V 5.75 A 0.75,0.75 0 0 0 13.25,5 Z M 6,3 C 4.3520357,3 3,4.3520357 3,6 v 12 c 0,1.647963 1.3520358,3 3,3 h 12 c 1.647963,0 3,-1.352037 3,-3 V 7.5 C 21.00048,7.300903 20.92178,7.1097827 20.78125,6.96875 l -3.75,-3.75 C 16.890217,3.0782166 16.699097,2.99952 16.5,3 h -0.75 -9.5 z m 1,1.5 h 8 a 0.750075,0.750075 0 0 1 0.75,0.75 v 3.5 A 0.750075,0.750075 0 0 1 15,9.5 H 7 A 0.750075,0.750075 0 0 1 6.25,8.75 V 5.25 A 0.750075,0.750075 0 0 1 7,4.5 Z m 0,7.75 H 17 A 0.750075,0.750075 0 0 1 17.75,13 v 5 A 0.750075,0.750075 0 0 1 17,18.75 H 7 A 0.750075,0.750075 0 0 1 6.25,18 V 13 A 0.750075,0.750075 0 0 1 7,12.25 Z"),
        ),
    )
}
