// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func H5Outline(p icons.IconProps) htmx.Node {
    return htmx.SVG(
        htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
        htmx.Attribute("viewBox", "0 0 24 24"),
        htmx.Merge(
            htmx.ClassNames{
                "h-5": true,
                "h-6": false,
                "w-5": true,
                "w-6": false,
            },
            p.ClassNames,
        ),
        htmx.Path(
            htmx.Attribute("stroke-linecap", "round"),
            htmx.Attribute("stroke-linejoin", "round"),
            htmx.Attribute("d", "m 21.5,9.7517064 -4.5,-8.46e-4 -0.25,4.7500006 2.5,-3e-6 c 1.75,-2e-6 2.25,1.000003 2.25,2.250003 0,1 0,2.5 -1.536,2.701843 -1.155465,0.09219 -2.067684,0.05193 -3.214,-0.119997 M 2.2470404,4.4962084 v 7.4999996 m 0,0 v 7.502 m 0,-7.501 H 12.74704 m 0,-7.4999996 v 7.4999996 m 0,0 v 7.501"),
        ),
    )
}
