// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func LockSemiOpenOutline(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
		htmx.Attribute("viewBox", "0 0 24 24"),
		htmx.Merge(
			htmx.ClassNames{
				"h-5": true,
				"h-6": false,
				"w-5": true,
				"w-6": false,
			},
			p.ClassNames,
		),
		htmx.Path(
			htmx.Attribute("stroke-linecap", "round"),
			htmx.Attribute("stroke-linejoin", "round"),
			htmx.Attribute("d", "m 16.5,10.5 v -5 C 16.5,3.01472 14.4853,1 12,1 9.5147,1 7.5,3.01472 7.5,5.5 V 7 M 6.75,21.75 h 10.5 c 1.2426,0 2.25,-1.0074 2.25,-2.25 v -6.75 c 0,-1.2426 -1.0074,-2.25 -2.25,-2.25 H 6.75 c -1.24264,0 -2.25,1.0074 -2.25,2.25 v 6.75 c 0,1.2426 1.00736,2.25 2.25,2.25 z"),
		),
	)
}
