// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func MicrophoneSlashOutline(p icons.IconProps) htmx.Node {
    return htmx.SVG(
        htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
        htmx.Attribute("viewBox", "0 0 24 24"),
        htmx.Merge(
            htmx.ClassNames{
                "h-5": true,
                "h-6": false,
                "w-5": true,
                "w-6": false,
            },
            p.ClassNames,
        ),
        htmx.Path(
            htmx.Attribute("stroke-linecap", "round"),
            htmx.Attribute("stroke-linejoin", "round"),
            htmx.Attribute("d", "M 3,3 21,21 M 16.601458,16.60053 A 6,6 0 0 0 18,12.75 v -1.5 M 8.9999997,8.9999995 9,4.5 a 3,3 0 1 1 6,0 v 8.25 a 3,3 0 0 1 -0.536894,1.712632 M 12,18.75 a 6,6 0 0 0 2.291834,-0.454958 M 12,18.75 a 6,6 0 0 1 -6,-6 v -1.5 m 6,7.5 v 3.75 m -3.75,0 h 7.5 m -4.019574,-6.762136 a 3,3 0 0 1 -2.7182897,-2.71829"),
        ),
    )
}
