// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func PasswordPencilOutline(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
		htmx.Attribute("viewBox", "0 0 24 24"),
		htmx.Merge(
			htmx.ClassNames{
				"h-5": true,
				"h-6": false,
				"w-5": true,
				"w-6": false,
			},
			p.ClassNames,
		),
		htmx.Path(
			htmx.Attribute("stroke-linecap", "round"),
			htmx.Attribute("stroke-linejoin", "round"),
			htmx.Attribute("d", "m 9.701,12.75 2.598076,-1.5 m 0,1.5 L 9.701,11.25 m 1.299038,-0.75 v 3 M 4.951,12.75 7.549076,11.25 m 0,1.5 L 4.951,11.25 M 6.250038,10.5 v 3 M 14.5,7.75 H 4.75 C 3.507361,7.75 2.5,8.757361 2.5,10 v 4 c 0,1.242599 1.007361,2.25 2.25,2.25 h 14.5 c 1.242599,0 2.25,-1.007401 2.25,-2.25 V 12.5 M 19.567669,6.3114812 c 0.577777,-0.5778015 1.521059,-0.5713374 2.106811,0.014439 0.585831,0.5857822 0.592294,1.5290496 0.01444,2.1068551 l -3.808707,3.8087617 c -0.417199,0.417117 -0.933172,0.722404 -1.501339,0.888057 l -2.128909,0.62086 0.620842,-2.128916 c 0.165695,-0.568128 0.470918,-1.084131 0.888092,-1.501329 z"),
		),
	)
}
