// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func PinOutline(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
		htmx.Attribute("viewBox", "0 0 24 24"),
		htmx.Merge(
			htmx.ClassNames{
				"h-5": true,
				"h-6": false,
				"w-5": true,
				"w-6": false,
			},
			p.ClassNames,
		),
		htmx.Path(
			htmx.Attribute("stroke-linecap", "round"),
			htmx.Attribute("stroke-linejoin", "round"),
			htmx.Attribute("d", "m 9.000016,14.999985 -6,6 m 12,-15.0000004 -1,-1 2,-2 5,5 -2,2 -1,-0.9999997 -4.5,4.5000001 c 1.5,1.5 1,4 -0.5,5.5 l -8,-8 c 1.5,-1.5000004 4,-2.0000004 5.5,-0.5 z"),
		),
	)
}
