// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func ShieldSolid(p icons.IconProps) htmx.Node {
    return htmx.SVG(
        htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
        htmx.Attribute("viewBox", "0 0 24 24"),
        htmx.Merge(
            htmx.ClassNames{
                "h-5": false,
                "h-6": true,
                "w-5": false,
                "w-6": true,
            },
            p.ClassNames,
        ),
        htmx.Path(
            htmx.Attribute("d", "m 12.516003,2.1269988 c -0.289324,-0.2742893 -0.742676,-0.2742893 -1.032,0 -2.1227312,2.015881 -4.9498755,3.1213279 -7.8769997,3.08 -0.3272549,-0.00425 -0.6194791,0.2041892 -0.722,0.515 -0.422027,1.2861636 -0.6363819,2.6313672 -0.635,3.985 0,5.9420002 4.064,10.9330002 9.5629997,12.3480002 0.122661,0.03163 0.251339,0.03163 0.374,0 5.499,-1.415 9.563,-6.406 9.563,-12.3480002 0,-1.39 -0.223,-2.73 -0.635,-3.985 -0.102169,-0.3112065 -0.394477,-0.5201136 -0.722,-0.516 l -0.143,0.001 c -2.996,0 -5.717,-1.17 -7.734,-3.08 z"),
        ),
    )
}
