// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func TriangleSolid(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
		htmx.Attribute("viewBox", "0 0 24 24"),
		htmx.Merge(
			htmx.ClassNames{
				"h-5": false,
				"h-6": true,
				"w-5": false,
				"w-6": true,
			},
			p.ClassNames,
		),
		htmx.Path(
			htmx.Attribute("d", "m 9.4014369,3.0268325 c 1.1544701,-2.00111 4.0426701,-2.00111 5.1970701,0 l 7.3544,12.7475005 c 1.1538,1.999999 -0.2896,4.4992 -2.5986,4.4992 H 4.6456669 c -2.30897,0 -3.75239901,-2.499201 -2.59855,-4.4992 z"),
		),
	)
}
