// Code generated by herogen; DO NOT EDIT.
package heroicons

import (
	htmx "github.com/katallaxie/htmx"
	"github.com/katallaxie/htmx/icons"
)

func ViewSplitSolid(p icons.IconProps) htmx.Node {
	return htmx.SVG(
		htmx.Attribute("xmlns", "http://www.w3.org/2000/svg"),
		htmx.Attribute("viewBox", "0 0 24 24"),
		htmx.Merge(
			htmx.ClassNames{
				"h-5": false,
				"h-6": true,
				"w-5": false,
				"w-6": true,
			},
			p.ClassNames,
		),
		htmx.Path(
			htmx.Attribute("d", "m 12.75,3.75 v 16.5 h 7.125 c 1.034999,0 1.875,-0.840001 1.875,-1.875 V 5.625 C 21.75,4.589001 20.909999,3.75 19.875,3.75 Z m -8.625,0 h 7.125 v 16.5 H 4.125 C 3.089466,20.25 2.25,19.410534 2.25,18.375 V 5.625 C 2.25,4.589 3.09,3.75 4.125,3.75 Z"),
		),
	)
}
